### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by Rudloff** [chalk/chalk-cli#6]
Hello,

I get this error when trying to run cli.js:

```
/var/www/node_modules/chalk-cli/templates.js:19
const takeWhileReverse = (array, predicate, start = -1) => {
                                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/node_modules/chalk-cli/cli.js:7:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by sindresorhus** [comment]
Upgrade Node.js: https://github.com/chalk/chalk-cli/blob/d704008c11dc50bbd228b3708a7ef428e33e6044/package.json#L21
